### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by GaneshKandu** [junepaik/cadmium-cms#1]
Hi My Name is Ganesh
I am Trying to install cadmium in sub folder of my Apache
but it doesn't load css and javascript 
unable to install in sub folder
please suggest how to install in sub folder

**Comment by ant-d3v** [comment]
Hello, Ganesh.
Thank you for trying Cadmium CMS.
Actually, CMS does not support installing in subdirectory for now.
But I'll work on this issue and release a new version which fixes the problem tomorrow.
Please stay in contact.

**Comment by ant-d3v** [comment]
I've released a new version [0.1.2](https://github.com/junepaik/cadmium-cms/releases/tag/v.0.1.2) which supports installing in subdirectory.
All you need is to edit two lines in the CMS .htaccess file before installing.

Replace:

> SetEnv INSTALL_PATH /

with:

> SetEnv INSTALL_PATH /path/to/directory

and:

> RewriteBase /

with:

> RewriteBase /path/to/directory

After installation is finished don't forget to set a full url in admin settings:
http://[your-site.com]/path/to/directory

**Comment by GaneshKandu** [comment]
Thank you ! So Much For Help
-Ganesh Kandu

On 10/22/15, Anton Romanov notifications@github.com wrote:

> I released a new version 0.1.2 which supports installing in subdirectory.
> All you need is to edit two lines in the CMS .htaccess file before
> installing.
> 
> Replace:
> 
> > SetEnv INSTALL_PATH /
> 
> with:
> 
> > SetEnv INSTALL_PATH /path/to/directory
> 
> and:
> 
> > RewriteBase /
> 
> with:
> 
> > RewriteBase /path/to/directory
> 
> After installation is finished don't forget to set a full url in admin
> settings:
> http://[your-site.com]/path/to/directory
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/junepaik/cadmium-cms/issues/1#issuecomment-150227625

## 

[image: thank-you-feather-pen-ag1.gif (214×115)]

**Comment by ant-d3v** [comment]
You're welcome!
If you'll have any further questions, feel free to ask :)

**Comment by GaneshKandu** [comment]
I am still Getting error on  wamp " Fatal error: Can't use function
return value in write context in
<rootpath>\cadm819\engine\Framework\Engine.php on line 11 "

On 10/24/15, Anton Romanov notifications@github.com wrote:

> You're welcome!
> If you'll have any further questions, feel free to ask :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/junepaik/cadmium-cms/issues/1#issuecomment-150668559

## 

[image: thank-you-feather-pen-ag1.gif (214×115)]

**Comment by ant-d3v** [comment]
Sorry. I've been testing Cadmium on PHP 5.6 and missed this error appears on version 5.4.
Now i fixed it! Everything else seems to work fine. No more fatal errors, I hope :)

Check out a new version [0.1.3](https://github.com/junepaik/cadmium-cms/releases/tag/v.0.1.3).
Thank you for patience, Ganesh!

**Comment by GaneshKandu** [comment]
Thanks a Lot ! , Now Its working  <img src='https://www.dokuwiki.org/lib/images/smileys/icon_wink.gif'/>

**Comment by GaneshKandu** [comment]
<a href="http://cadmium-cms.com/" >http://cadmium-cms.com</a> is still displaying 0.1.1 for downloads
